### ISSUE TITLE
Question about tank and tamples dataset

### ISSUE THREAD

**Issue by gaobodaxinwen** [jzhangbs/MVSDF#4]
Thanks again for sharing this great work. I have found that the results on tank and temples dataset only contains the horse and statues, while the floor and trees are not reconstructed. I am curious how you got this results. Do you have mask for those Interesting part or you remove floor and trees after reconstruction ?

**Comment by jzhangbs** [comment]
The bounding box of the scene is tight, it only contains the main statue part.

**Comment by gaobodaxinwen** [comment]
Thanks for your reply. How can I get the bounding box annotation？

**Comment by jzhangbs** [comment]
You can generate a point cloud for this scene, manually crop it and calculate a bounding box for the remaining points.

**Comment by gaobodaxinwen** [comment]
Thanks for your advice, I will try it.
