### ISSUE TITLE
DTU evaluation 结果

### ISSUE THREAD

**Issue by decai-chen** [jzhangbs/MVSDF#5]
作者你好，
我发现在你的两篇文章里（MVSDF和Vis-MVSNet），对于Vis-MVSNet在DTU上的evlauation的结果的差距比较大，如下图所示，一个是0.88，一个是0.365。如果我没有理解错的话，Chamfer（L1） 就是Acc. Comp.的平均数，也就是overall。如果两个指标应该是同一个意思，为什么在两篇论文里会差距这么大呢？请多多指教，谢谢！
![image](https://user-images.githubusercontent.com/37768417/178285533-954c7bfc-2141-4c7e-92db-3ed77cd817bb.png)
![image](https://user-images.githubusercontent.com/37768417/178285706-78423544-fbd1-48f1-abbe-efbb29d38d72.png)

**Comment by jzhangbs** [comment]
有这么几点不同
- Vis-MVSNet是用点云测出来的，MVSDF这组是用sPSR转换成mesh测出来的
- MVSDF这组用的num source view和filtering条件不太一样

**Comment by decai-chen** [comment]
明白了，非常感谢！
