### ISSUE TITLE
Gradients of the feature consistency loss

### ISSUE THREAD

**Issue by morsingher** [jzhangbs/MVSDF#9]
Hi, thanks for releasing this work. 

I have a question about equation 7 in your paper, where you derive the gradients of the feature consistency loss with respect to network parameters. Why is it necessary to compute them explicitly? Intuitively, I would think that PyTorch autograd will figure them out automatically and in your code I couldn't find the corresponding explicit computation. If I missed it, can you point me to the correct line?

Thank you in advance!

**Comment by jzhangbs** [comment]
Hi @morsingher, yes in current implementation the gradients are automatically computed by PyTorch. The analysis in the paper is given to show why the feature consistency loss can affect the geometry. 

And optionally we can use Sobel operator to calculate the image gradient which possibly improves the robustness. In this case we need to explicitly calculate the gradients.

**Comment by morsingher** [comment]
Thanks for the quick answer, closing this as my doubt is cleared :)
